from distutils.core import setup
setup(
  name = 'solarized',
  packages = ['solarized'],
  version = '1.2.5',
  description = 'Solarized theme terminal string colors with zero dependencies and function calls',
  author = 'Rob Muhlestein',
  author_email = 'rob@skilstak.com',
  url = 'https://github.com/skilstak/solarized', 
  download_url = 'https://github.com/skilstak/solarized/tarball/1.2.5',
  keywords = [
    "solarized",
    "color",
    "colour",
    "colors",
    "terminal",
    "console",
    "cli",
    "string",
    "str",
    "ansi",
    "style",
    "styles",
    "tty",
    "formatting",
    "rgb",
    "256",
    "shell",
    "xterm",
    "log",
    "logging",
    "command-line",
    "text"
  ],
  classifiers = [],
)
